Active: 1

PlatformSets:
 - ondemand-otrs6

DeployOTRSBranch: rel-6_0

DeployOTRSPackages:
 - OTRSCodePolicy@rel-6_0
 - GeneralCatalog@rel-6_0
 - ITSMCore@rel-6_0
 - ITSMIncidentProblemManagement@rel-6_0
 - ImportExport@rel-6_0
